ARG PARENT_IMAGE_NAME
ARG PARENT_IMAGE_TAG

FROM ${PARENT_IMAGE_NAME}:${PARENT_IMAGE_TAG}

COPY /dist/*.jar ./

EXPOSE ${MICROSERVICE_PORT}

ENTRYPOINT java ${JAVA_OPTS} \
	-Djava.security.egd=file:/dev/./urandom \
	-jar ${DIRPATH}/${MICROSERVICE_NAME}.jar
