ARG PARENT_IMAGE_NAME
ARG PARENT_IMAGE_TAG

FROM ${PARENT_IMAGE_NAME}:${PARENT_IMAGE_TAG}

COPY /dist/*.jar ./

EXPOSE ${MICROSERVICE_PORT}

ENTRYPOINT /opt/jdk/bin/java ${DEFAULT_JAVA_OPTS} ${JAVA_OPTS} \
	-jar ${DIRPATH}/${MICROSERVICE_NAME}.jar
