#oauth
oauth.server=http://localhost:8081

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.name=redmic
spring.datasource.url=jdbc:postgresql://localhost:5432/redmic?currentSchema=app

property.SUPERSET_API_URL=https://superset.ecomarcan.grafcan.es

logging.level.es.redmic=debug
